#!/bin/bash

theme="/home/$USER/.config/rofi/config/edit.rasi"

export $(grep -v '^#' /home/$USER/.config/hyprgnome/.env | xargs)

options=("1. View / Edit shortcuts.conf" "2. View / Edit env.conf" "3. Reinstall Vencord" "4. Reload shortcuts")

selected_option=$(printf "%s\n" "${options[@]}" | $ROFI -dmenu -p "" -theme $theme)

case "$selected_option" in
"1. View / Edit shortcuts.conf")
    $TERMINAL $EDITOR $HOME/.config/hyprgnome/shortcuts.conf
	;;
"2. View / Edit env.conf")
    $TERMINAL $EDITOR $HOME/.config/hyprgnome/.env
	;;
"3. Reinstall Vencord")
    $TERMINAL $HOME/reinstall_discord.sh
	;;
"4. Reload shortcuts")
    $HOME/.config/hyprgnome/load-shortcuts.sh
	;;
*) ;;
esac