#!/bin/bash

theme="/home/$USER/.config/rofi/config/open.rasi"

export $(grep -v '^#' /home/$USER/.config/hyprgnome/.env | xargs)

folders=( $(find ~/sgoinfre/private/WIP42projects -maxdepth 1 -mindepth 1 -type d) $(find ~/sgoinfre/private/finished_42_projects -maxdepth 1 -mindepth 1 -type d) )

# Extract folder names (basename) for rofi display
names=()
for f in "${folders[@]}"; do
    names+=("$(basename "$f")")
done

# Show folder names in rofi
chosen_name=$(printf '%s\n' "${names[@]}" | $ROFI -dmenu -theme "$theme")

# Find full path matching chosen name
for i in "${!names[@]}"; do
    if [[ "${names[i]}" == "$chosen_name" ]]; then
        chosen_folder="${folders[i]}"
        break
    fi
done

# Open kitty in chosen folder if any
if [[ -n "$chosen_folder" ]]; then
    $TERMINAL --directory "$chosen_folder"
fi